import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { migrationNames } from '../scripts/phase3-bundle.mjs';

const owner = '11111111-1111-4111-8111-111111111111';
const admin = '22222222-2222-4222-8222-222222222222';
const other = '33333333-3333-4333-8333-333333333333';
const requestId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const draft = { name:'New creature',species:'beast',universe:'Universe',galaxy:'',planet:'Planet',world:'',age:'',size:'',element:'',rarity:'',powerSource:'',threatLevel:'B',description:'A sufficiently long creature description.',appearance:'',weaknesses:'Light',limitations:'',strongestAbilityCondition:'',abilities:[{name:'Portal',description:'Open a portal.'}] };
const bootstrap = await readFile(new URL('./sql/bootstrap.sql',import.meta.url),'utf8');
const migrations = await Promise.all(migrationNames.map(name => readFile(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8')));

for (const idType of ['bigint','uuid']) {
  let db, existingId;
  before(async () => {
    // Separate fixture databases prove both supported ID families; never connect online.
    db = new PGlite();
    const fixture = idType === 'uuid' ? bootstrap.replace('id bigint generated by default as identity primary key,creator_id','id uuid default gen_random_uuid() primary key,creator_id').replace('creature_id bigint references','creature_id uuid references') : bootstrap;
    await db.exec(fixture);
    for (const sql of migrations) await db.exec(sql);
    existingId = (await db.query('select id from public.creatures')).rows[0].id;
  });
  after(async () => { await db?.close(); });
  async function as(role, uid, fn) {
    await db.exec(`begin; set local role ${role};`);
    await db.query("select set_config('request.jwt.claim.sub',$1,true)",[uid || '']);
    try { return await fn(); } finally { await db.exec('rollback'); }
  }
  async function denied(sql,params=[]) {
    await db.exec('savepoint denied');
    let error;
    try { await db.query(sql,params); } catch (e) { error=e; }
    await db.exec('rollback to savepoint denied; release savepoint denied');
    assert.ok(error,`Expected a database rejection: ${sql}`);
    return error;
  }
  const submit = (value=draft,image=null) => db.query('select public.mca_submit_creature($1,$2::jsonb,$3) as creature',[requestId,JSON.stringify(value),image]);
  const review = (id,status,level) => db.query('select public.mca_review_creature($1,$2,$3)',[String(id),status,level]);

  test(`${idType}: migration preserves existing data and archive remains public`, async () => {
    await as('anon',null,async () => {
      assert.equal((await db.query('select name from public.creatures')).rows[0].name,'Existing creature');
      await denied('select * from public.profiles');
      await denied('select * from public.creature_favorites');
      await denied('select public.mca_submit_creature($1,$2::jsonb,null)',[requestId,JSON.stringify(draft)]);
    });
  });
  test(`${idType}: audit emits a single complete JSON result without writes`,async()=>{
    const report=(await db.query(await readFile(new URL('../supabase/audit.sql',import.meta.url),'utf8'))).rows;
    assert.equal(report.length,1);
    const audit=JSON.parse(report[0].mca_audit);
    assert.equal(audit.tables.length,5);assert.ok(audit.columns.length>35);
    assert.ok(audit.functions.some(fn=>fn.signature.startsWith('mca_submit_creature')));
  });
  test(`${idType}: profiles isolate accounts and prohibit role/reputation escalation`, async () => {
    await as('authenticated',owner,async () => {
      assert.equal((await db.query('select * from public.profiles')).rows.length,1);
      assert.equal((await db.query('update public.profiles set username=$1 where id=$2 returning id',['Renamed',other])).rows.length,0);
      assert.equal((await db.query('update public.profiles set username=$1 where id=$2 returning username',['Renamed',owner])).rows[0].username,'Renamed');
      await denied('update public.profiles set role=$1 where id=$2',['admin',owner]);
      await denied('update public.profiles set reputation=999 where id=$1',[owner]);
      await denied('insert into public.profiles(id,role) values($1,$2)',[owner,'admin']);
    });
  });
  test(`${idType}: direct creature/ability writes and retired review RPC are denied`, async () => {
    await as('authenticated',owner,async () => {
      await denied('update public.creatures set status=$1,verified_threat_level=$2 where id=$3',['verified','X',existingId]);
      await denied('delete from public.creatures where id=$1',[existingId]);
      await denied('insert into public.creature_abilities(creature_id,ability_name) values($1,$2)',[existingId,'Injected']);
      await denied('select public.admin_review_creature(1,$1,$2)',['verified','X']);
      await denied('select public.mca_review_creature($1,$2,$3)',[String(existingId),'verified','X']);
    });
  });
  test(`${idType}: atomic submission generates code, ignores privileged payload and deduplicates retry`, async () => {
    await as('authenticated',owner,async () => {
      const value = {...draft,creator_id:other,status:'verified',verified_threat_level:'X'};
      const first = (await submit(value)).rows[0].creature;
      const retry = (await submit(value)).rows[0].creature;
      assert.equal(first.id,retry.id); assert.equal(first.creator_id,owner); assert.equal(first.status,'pending'); assert.equal(first.verified_threat_level,null);
      assert.match(first.creature_code,idType==='uuid'?/^MCA-/:/^VX-/);
      assert.equal((await db.query('select count(*)::int as count from public.creatures')).rows[0].count,2);
      assert.equal((await db.query('select count(*)::int as count from public.creature_abilities')).rows[0].count,1);
      await denied('select * from public.mca_submission_requests');
      assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,null)',[requestId,JSON.stringify({...value,name:'Changed'})])).message,/REQUEST_CONFLICT/);
    });
  });
  test(`${idType}: request tombstone prevents recreating a record deleted by an operator`,async()=>{
    await db.exec('begin');
    try {
      await db.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);
      const created=(await submit()).rows[0].creature;
      await db.query('delete from public.creatures where id=$1',[created.id]);
      assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,null)',[requestId,JSON.stringify(draft)])).message,/REQUEST_RECORD_REMOVED/);
      assert.equal((await db.query('select count(*)::int as count from public.creatures')).rows[0].count,1);
    } finally { await db.exec('rollback'); }
  });
  test(`${idType}: invalid input and ability failure roll back parent and request atomically`, async () => {
    await as('authenticated',owner,async () => {
      for (const bad of [{...draft,description:'short'},{...draft,abilities:[]},{...draft,abilities:Array(6).fill(draft.abilities[0])},{...draft,abilities:[{name:'',description:''}]},{...draft,abilities:[{name:7,description:''}]},{...draft,threatLevel:'hacked'}]) {
        assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,null)',[requestId,JSON.stringify(bad)])).message,/DRAFT_INVALID/);
      }
      assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,null)',[requestId,JSON.stringify({...draft,abilities:[{name:'FORCE_DB_FAILURE',description:''}]})])).message,/TEST_DB_FAILURE/);
      assert.equal((await db.query('select count(*)::int as count from public.creatures')).rows[0].count,1);
      assert.equal((await db.query('select count(*)::int as count from public.creature_abilities')).rows[0].count,0);
      await submit(); // The same UUID remains usable after a rolled-back transaction.
    });
  });
  test(`${idType}: favorites are unique, private and cannot be inserted for another user`, async () => {
    await as('authenticated',owner,async () => {
      await db.query('insert into public.creature_favorites(user_id,creature_id) values($1,$2) on conflict do nothing',[owner,existingId]);
      await db.query('insert into public.creature_favorites(user_id,creature_id) values($1,$2) on conflict do nothing',[owner,existingId]);
      assert.equal((await db.query('select * from public.creature_favorites')).rows.length,1);
      await denied('insert into public.creature_favorites(user_id,creature_id) values($1,$2)',[other,existingId]);
      await denied('update public.creature_favorites set user_id=$1',[other]);
      await db.query("select set_config('request.jwt.claim.sub',$1,true)",[other]);
      assert.equal((await db.query('select * from public.creature_favorites')).rows.length,0);
      assert.equal((await db.query('delete from public.creature_favorites returning *')).rows.length,0);
      await db.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);
      assert.equal((await db.query('delete from public.creature_favorites returning *')).rows.length,1);
    });
  });
  test(`${idType}: review RPC validates admin and rejects invalid official threat`, async () => {
    await as('authenticated',admin,async () => {
      await review(existingId,'verified','S');
      assert.equal((await db.query('select verified_threat_level from public.creatures where id=$1',[existingId])).rows[0].verified_threat_level,'S');
      await denied('select public.mca_review_creature($1,$2,null)',[String(existingId),'verified']);
      await denied('select public.mca_review_creature($1,$2,$3)',[String(existingId),'canon','X']);
      await review(existingId,'investigation','X');
      assert.equal((await db.query('select verified_threat_level from public.creatures where id=$1',[existingId])).rows[0].verified_threat_level,null);
    });
  });
  test(`${idType}: images enforce owner/path/type/size and protect a committed image`, async () => {
    await as('authenticated',owner,async () => {
      const image = `${owner}/${requestId}.png`;
      await denied('insert into storage.objects(bucket_id,name,owner_id) values($1,$2,$3)',['creature-images',`${other}/image.png`,owner]);
      await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata) values($1,$2,$3,$4::jsonb)',['creature-images',image,owner,JSON.stringify({mimetype:'image/png',size:99})]);
      const created=(await submit(draft,image)).rows[0].creature;
      assert.equal(created.image_url,`/storage/v1/object/public/creature-images/${image}`);
      assert.equal((await db.query('delete from storage.objects where name=$1 returning *',[image])).rows.length,0);
      assert.equal((await db.query('update storage.objects set name=$1 returning *',['other.png'])).rows.length,0);
      await db.query("select set_config('request.jwt.claim.sub',$1,true)",[other]);
      assert.equal((await db.query('select * from storage.objects')).rows.length,0);
      assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,$3)',[requestId,JSON.stringify(draft),image])).message,/IMAGE_INVALID/);
      await db.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);
      const unused=`${owner}/unused.png`;
      await db.query('insert into storage.objects(bucket_id,name,owner_id) values($1,$2,$3)',['creature-images',unused,owner]);
      assert.equal((await db.query('delete from storage.objects where name=$1 returning *',[unused])).rows.length,1);
    });
  });
  test(`${idType}: invalid image metadata and anonymous identity cannot use the submission RPC`,async()=>{
    await as('authenticated',null,async()=>{
      assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,null)',[requestId,JSON.stringify(draft)])).message,/AUTH_REQUIRED/);
    });
    for (const metadata of [{mimetype:'image/svg+xml',size:100},{mimetype:'image/png',size:5242881}]) {
      await as('authenticated',owner,async()=>{
        const image=`${owner}/${requestId}.png`;
        await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata) values($1,$2,$3,$4::jsonb)',['creature-images',image,owner,JSON.stringify(metadata)]);
        assert.match((await denied('select public.mca_submit_creature($1,$2::jsonb,$3)',[requestId,JSON.stringify(draft),image])).message,/IMAGE_INVALID/);
      });
    }
  });
}
