import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {auditedSchema} from './support/audited-schema.mjs';
import {phase3Bundle} from '../scripts/phase3-bundle.mjs';
import {originsBundle} from '../scripts/origins-bundle.mjs';
import {traitsBundle} from '../scripts/traits-bundle.mjs';
const owner='11111111-1111-4111-8111-111111111111',admin='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333';
const request='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';let db;
const legacy={name:'Trait creature',species:'beast',universe:'Old universe',galaxy:'Old galaxy',planet:'Old planet',world:'',age:'',size:'Old size',element:'fire',rarity:'epic',powerSource:'',threatLevel:'SS',description:'A sufficiently long creature description.',appearance:'',weaknesses:'Light',limitations:'',strongestAbilityCondition:'',abilities:[{name:'Portal',description:''}]};
before(async()=>{db=new PGlite();await db.exec(auditedSchema());for(const id of [owner,admin,other])await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2::jsonb)',[id,'{"username":"Tester"}']);await db.query("update public.profiles set role='admin' where id=$1",[admin]);await db.exec(await phase3Bundle());await db.exec(await originsBundle());assert.equal((await db.exec(await traitsBundle())).at(-1).rows[0].mca_traits_ready,true);});
after(async()=>{await db?.close();});
async function as(uid,fn){await db.exec(`begin;set local role ${uid?'authenticated':'anon'};`);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[uid||'']);try{return await fn();}finally{await db.exec('rollback');}}
async function denied(sql,args=[]){await db.exec('savepoint denied');let error;try{await db.query(sql,args);}catch(e){error=e;}await db.exec('rollback to savepoint denied;release savepoint denied');assert.ok(error,sql);return error;}
const add=async(kind,name)=>(await db.query('select public.mca_add_term($1,$2) as term',[kind,name])).rows[0].term;
async function draft(){let leaf=null;for(const kind of ['universe','galaxy','nebula','star_system','planet'])leaf=(await db.query('select public.mca_add_origin($1,$2,$3) as node',[kind,`Trait ${kind}`,leaf?.id||null])).rows[0].node;
const rows=(await db.query("select id,code from public.creature_terms where code in ('beast','fire','water')")).rows;
return {...legacy,traitsVersion:1,speciesTermId:rows.find(n=>n.code==='beast').id,elementTermIds:rows.filter(n=>n.code!=='beast').map(n=>n.id),originPlanetId:leaf.id,rarity:'genesis',threatLevel:'T7',dimensions:{height:{value:'0.000000000001',unit:'nm'},length:{value:'123456789012345678901234567890',unit:'ly'},width:{value:'',unit:'m'}}};}
const submit=async(d,id=request)=>(await db.query('select public.mca_submit_creature_v2($1,$2::jsonb,null) as creature',[id,JSON.stringify(d)])).rows[0].creature;
test('delivered trait bundle matches exactly and seeds only the existing species/elements',async()=>{assert.equal(await readFile(new URL('../supabase/apply-traits.sql',import.meta.url),'utf8'),await traitsBundle());assert.equal((await db.query('select count(*)::int as n from public.creature_terms')).rows[0].n,22);});
test('anonymous users cannot propose, review, submit or read submitter identity',async()=>{await as(null,async()=>{assert.equal((await db.query('select id,kind,code,name from public.creature_terms')).rows.length,22);await denied('select created_by from public.creature_terms');await denied("select public.mca_add_term('species','Injected')");await denied('select public.mca_submit_creature_v2($1,$2,null)',[request,JSON.stringify(legacy)]);});});
test('proposals deduplicate per kind, remain private and cannot be reviewed by ordinary users',async()=>{await as(owner,async()=>{const a=await add('species',' New  species ');assert.equal((await add('species','new species')).id,a.id);assert.notEqual((await add('element','new species')).id,a.id);await denied('insert into public.creature_terms(kind,code,name) values($1,$2,$3)',['species','injected','Injected']);await denied('select public.mca_review_term($1,$2,null)',[a.id,'approved']);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[other]);assert.equal((await db.query('select id from public.creature_terms where id=$1',[a.id])).rows.length,0);assert.match((await denied("select public.mca_add_term('species','new species')")).message,/RESERVED/);});});
test('admin approval exposes proposals publicly; rejected proposals remain unusable',async()=>{await as(owner,async()=>{const a=await add('species','Approved species');const b=await add('element','Rejected element');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[admin]);await db.query('select public.mca_review_term($1,$2,null)',[a.id,'approved']);await db.query('select public.mca_review_term($1,$2,$3)',[b.id,'rejected','Correct the name']);await db.exec('set local role anon');assert.equal((await db.query('select id from public.creature_terms where id=$1',[a.id])).rows.length,1);assert.equal((await db.query('select id from public.creature_terms where id=$1',[b.id])).rows.length,0);});});
test('submission resolves canonical species/elements, exact decimal units and all new ranks atomically',async()=>{await as(owner,async()=>{const d=await draft();const custom=await add('species','Quantum species');d.speciesTermId=custom.id;const c=await submit(d);assert.equal(c.species_name,'Quantum species');assert.equal(c.species,custom.code);assert.deepEqual(c.element_names.sort(),['Lửa','Nước']);assert.deepEqual(c.dimensions,d.dimensions);assert.equal(c.rarity,'genesis');assert.equal(c.proposed_threat_level,'T7');assert.equal((await db.query('select count(*)::int as n from public.creature_elements')).rows[0].n,2);assert.equal((await submit(d)).id,c.id);assert.match((await denied('select public.mca_submit_creature_v2($1,$2,null)',[request,JSON.stringify({...d,rarity:'god'})])).message,/CONFLICT/);});});
test('cannot steal pending terms, use a species as an element, repeat elements or forge IDs',async()=>{await as(owner,async()=>{const d=await draft();await db.query("select set_config('request.jwt.claim.sub',$1,true)",[other]);const foreign=await add('species','Other species');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);for(const bad of [{...d,speciesTermId:foreign.id},{...d,elementTermIds:[d.speciesTermId]},{...d,elementTermIds:[d.elementTermIds[0],d.elementTermIds[0]]},{...d,elementTermIds:['invalid']}])await denied('select public.mca_submit_creature_v2($1,$2,null)',[request,JSON.stringify(bad)]);assert.equal((await db.query('select count(*)::int as n from public.creatures')).rows[0].n,0);});});
test('dimensions reject text, negative, zero, exponent, excess precision and units outside the range',async()=>{await as(owner,async()=>{const d=await draft();for(const value of ['abc','-1','0','1e9','NaN','1.1234567890123','9'.repeat(31)])await denied('select public.mca_submit_creature_v2($1,$2,null)',[request,JSON.stringify({...d,dimensions:{...d.dimensions,height:{value,unit:'m'}}})]);await denied('select public.mca_submit_creature_v2($1,$2,null)',[request,JSON.stringify({...d,dimensions:{...d.dimensions,height:{value:'1',unit:'parsec'}}})]);});});
test('new forms reject retired ranks and rarity codes; admin supports the modern hierarchy',async()=>{await as(owner,async()=>{const d=await draft();for(const bad of [{...d,threatLevel:'SS'},{...d,rarity:'epic'}])await denied('select public.mca_submit_creature_v2($1,$2,null)',[request,JSON.stringify(bad)]);const c=await submit(d);await denied('select public.mca_review_creature($1,$2,$3)',[String(c.id),'verified','T2']);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[admin]);await db.query('select public.mca_review_creature($1,$2,$3)',[String(c.id),'verified','T2']);assert.equal((await db.query('select verified_threat_level from public.creatures where id=$1',[c.id])).rows[0].verified_threat_level,'T2');await denied('select public.mca_review_creature($1,$2,$3)',[String(c.id),'verified','X']);});});
test('lost-response retries remain valid after catalog rejection and failed abilities roll back',async()=>{await as(owner,async()=>{const d=await draft();const s=await add('species','Retry species');d.speciesTermId=s.id;const c=await submit(d);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[admin]);await db.query('select public.mca_review_term($1,$2,null)',[s.id,'rejected']);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);assert.equal((await submit(d)).id,c.id);const fresh=await draft();await denied('select public.mca_submit_creature_v2($1,$2,null)',['bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',JSON.stringify({...fresh,abilities:[]})]);assert.equal((await db.query('select count(*)::int as n from public.creatures')).rows[0].n,1);});});
test('old submissions and SS/X records keep their text dimensions, rarity and exact retry behavior',async()=>{await as(owner,async()=>{const a=(await db.query('select public.mca_submit_creature($1,$2,null) as c',[request,JSON.stringify(legacy)])).rows[0].c;const b=(await db.query('select public.mca_submit_creature($1,$2,null) as c',[request,JSON.stringify(legacy)])).rows[0].c;assert.equal(a.id,b.id);assert.equal(a.size,'Old size');assert.equal(a.rarity,'epic');assert.equal(a.traits_version,null);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[admin]);await db.query('select public.mca_review_creature($1,$2,$3)',[String(a.id),'verified','X']);});});
