import {test,expect,type Page} from '@playwright/test';
test.skip(process.env.MCA_TEST_TRAITS!=='1','Run npm run test:traits');
const backend='http://127.0.0.1:54399';
test.beforeEach(async({request})=>{await request.post(`${backend}/__test/reset`);});
async function login(page:Page,admin=false,path='/tao-ho-so'){await page.goto(`/dang-nhap?next=${encodeURIComponent(path)}`);await page.locator('#loginEmail').fill(admin?'admin@example.com':'test@example.com');await page.locator('#loginPassword').fill('mock-password');await page.locator('#loginButton').click();await expect(page).toHaveURL(new RegExp(path.split('?')[0]));}
async function fill(page:Page){await page.locator('#creatureName').fill('Sinh vật đa nguyên tố');await page.locator('#creatureSpecies').selectOption({label:'Thú'});for(const [index,kind] of ['universe','galaxy','nebula','star_system','planet'].entries())await page.locator(`#origin-${kind}`).selectOption(`aaaaaaaa-aaaa-4aaa-8aaa-${String(index+1).padStart(12,'0')}`);await page.locator('#creatureThreat').selectOption('T3');await page.locator('#creatureRarity').selectOption('god');await page.locator('#creatureDescription').fill('Một mô tả đủ dài cho sinh vật đa nguyên tố và ba kích thước.');await page.locator('#creatureWeaknesses').fill('Ánh sáng');await page.locator('#abilityName0').fill('Dịch chuyển');}
async function propose(page:Page,kind:'species'|'element',name:string){await page.getByRole('button',{name:`+ Thêm ${kind==='species'?'loài sinh vật':'nguyên tố'}`,exact:true}).click();await page.locator(`#new-${kind}`).fill(name);await page.getByRole('button',{name:'Gửi đề xuất',exact:true}).click();if(kind==='species')await expect(page.locator('#creatureSpecies option:checked')).toContainText(name);else await expect(page.getByLabel(`${name} · Chờ duyệt`,{exact:true})).toBeChecked();}
test('seven bilingual rarity ranks, hierarchical threats and three numeric measurements restore with a draft',async({page})=>{
 await login(page);await fill(page);await expect(page.locator('#creatureRarity option')).toHaveText(['Chọn độ hiếm...','Phổ Thông / Normal','Dị Biệt / Special','Hiếm / Rare','Độc Nhất / Unique','Huyền Thoại / Legend','Thần Tính / God','Sáng Thế / Genesis']);
 await page.locator('#creatureThreat').selectOption('S');await expect(page.locator('#creatureThreat-planetary option')).toHaveText(['F','E','D','C','B','A','S — Đạt cấp (1) Phá Tinh']);await page.locator('#creatureThreat-planetary').selectOption('F');
 await page.locator('#dimension-height').fill('0.125');await page.locator('#unit-height').selectOption('nm');await page.locator('#dimension-length').fill('12');await page.locator('#unit-length').selectOption('ly');await page.getByLabel('Lửa',{exact:true}).check();await page.getByLabel('Nước',{exact:true}).check();await page.locator('#saveDraftButton').click();await page.reload();
 await expect(page.locator('#dimension-height')).toHaveValue('0.125');await expect(page.locator('#unit-length')).toHaveValue('ly');await expect(page.getByLabel('Lửa',{exact:true})).toBeChecked();await expect(page.getByLabel('Nước',{exact:true})).toBeChecked();await expect(page.locator('#creatureThreat-planetary')).toHaveValue('F');
});
test('multi-element submissions display all labels/units and the archive filters a non-first element',async({page,request})=>{
 await login(page);await fill(page);await page.getByLabel('Lửa',{exact:true}).check();await page.getByLabel('Nước',{exact:true}).check();await page.locator('#dimension-height').fill('2.5');await page.locator('#unit-height').selectOption('km');await page.locator('#dimension-width').fill('0.000001');await page.locator('#unit-width').selectOption('ly');await page.locator('.create-submit-button').click();await page.getByRole('link',{name:'Xem hồ sơ',exact:true}).click();
 await expect(page.locator('.mca-facts-grid')).toContainText('Lửa · Nước');await expect(page.locator('.mca-facts-grid')).toContainText('Cao: 2.5 km');await expect(page.locator('.mca-facts-grid')).toContainText('0.000001 năm ánh sáng');await expect(page.locator('.mca-facts-grid')).toContainText('Thần Tính / God');await expect(page.locator('.mca-threat-display')).toContainText('(3) Vẫn Hà');
 await page.goto('/kho-du-lieu');await page.locator('#archiveSearchInput').fill('Sinh vật đa nguyên tố');await page.locator('#archiveElement').selectOption('water');await expect(page.locator('.archive-creature-card')).toHaveCount(1);const state=await(await request.get(`${backend}/__test/state`)).json();expect(state.records.at(-1).element_codes).toContain('water');
});
test('proposed species/elements remain private until admin approves them',async({page,browser,request})=>{
 await login(page);await propose(page,'species','Loài lượng tử');await propose(page,'element','Thời gian');let publicTerms=await(await request.get(`${backend}/rest/v1/creature_terms`)).json();expect(publicTerms.some((n:{name:string})=>n.name==='Loài lượng tử'||n.name==='Thời gian')).toBe(false);
 const context=await browser.newContext();const admin=await context.newPage();await login(admin,true,'/admin-phan-loai');admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Duyệt Loài lượng tử',exact:true}).click();await expect(admin.getByRole('status').filter({hasText:'Đã duyệt'})).toContainText('Đã duyệt');await admin.locator('#termAdminKind').selectOption('element');admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Duyệt Thời gian',exact:true}).click();await expect(admin.getByRole('status').filter({hasText:'Đã duyệt'})).toContainText('Đã duyệt');
 publicTerms=await(await request.get(`${backend}/rest/v1/creature_terms`)).json();expect(publicTerms.filter((n:{name:string})=>n.name==='Loài lượng tử'||n.name==='Thời gian')).toHaveLength(2);await context.close();await page.goto('/admin-phan-loai');await expect(page.getByRole('heading',{name:'Không có quyền truy cập'})).toBeVisible();
});
test('numeric validation rejects exponent/zero and term errors remain retryable on mobile',async({page,request})=>{
 await login(page);await fill(page);await page.locator('#dimension-height').fill('0');await page.locator('.create-submit-button').click();await expect(page.locator('#createMessage')).toContainText('số lớn hơn 0');await page.locator('#dimension-height').fill('1e9');await page.locator('.create-submit-button').click();await expect(page.locator('#createMessage')).toContainText('số lớn hơn 0');await page.locator('#dimension-height').fill('1');
 await request.post(`${backend}/__test/fail`,{data:{addTerm:true}});await page.getByRole('button',{name:'+ Thêm nguyên tố',exact:true}).click();await page.locator('#new-element').fill('Nguyên tố mới');await page.getByRole('button',{name:'Gửi đề xuất',exact:true}).click();await expect(page.locator('.mca-term-picker [role="alert"]')).toContainText('Chưa xác nhận');await request.post(`${backend}/__test/fail`,{data:{addTerm:false}});await page.getByRole('button',{name:'Gửi đề xuất',exact:true}).click();await expect(page.getByLabel('Nguyên tố mới · Chờ duyệt',{exact:true})).toBeChecked();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/traits-mobile.png',fullPage:true});await page.locator('.mca-panel').first().screenshot({path:'test-results/traits-basic-mobile.png'});
});
test('lost-response modern submissions replay unchanged after reload',async({page,request})=>{
 await login(page);await fill(page);await page.getByLabel('Lửa',{exact:true}).check();await request.post(`${backend}/__test/fail`,{data:{submitResponseLost:true}});await page.locator('.create-submit-button').click();await expect(page.locator('#createMessage')).toContainText('Chưa xác nhận');await page.reload();await expect(page.locator('.create-submit-button')).toHaveText('KIỂM TRA LẠI YÊU CẦU');await page.locator('.create-submit-button').click();await expect(page.getByRole('heading',{name:'Sinh vật đa nguyên tố',exact:true})).toBeVisible();const state=await(await request.get(`${backend}/__test/state`)).json();expect(state.records).toHaveLength(26);const calls=state.calls.filter((c:{table:string})=>c.table==='submit_rpc');expect(calls[0].body).toEqual(calls[1].body);expect(calls[0].body.p_draft.traitsVersion).toBe(1);
});
test('admin assigns modern verified threat and the verified value controls archive filtering',async({page})=>{
 await login(page);await fill(page);await page.locator('.create-submit-button').click();await login(page,true,'/admin-chi-tiet?id=125');await page.locator('#adminThreatSelect').selectOption('T7');page.once('dialog',d=>d.accept());await page.locator('#verifyCreatureButton').click();await expect(page.locator('#reviewMessage')).toContainText('Đã cập nhật');await page.goto('/kho-du-lieu');await page.locator('#archiveSearchInput').fill('Sinh vật đa nguyên tố');await page.getByRole('button',{name:'(7) Quy Bản',exact:true}).click();await expect(page.locator('.archive-creature-card')).toHaveCount(1);
});

test('a pending legacy request is never upgraded while enabling the new form',async({page,request})=>{
 await login(page);await page.evaluate(()=>{
 const draft={name:'Hồ sơ cũ đang chờ',species:'beast',universe:'Vũ trụ cũ',galaxy:'',planet:'Hành tinh cũ',world:'',age:'',size:'3 mét',element:'fire',rarity:'epic',powerSource:'',threatLevel:'SS',description:'Mô tả đủ dài của hồ sơ đang gửi từ phiên bản cũ.',appearance:'',weaknesses:'Ánh sáng',limitations:'',strongestAbilityCondition:'',abilities:[{name:'Bay',description:''}]};
 localStorage.setItem('mcaCreatureSubmission:11111111-1111-4111-8111-111111111111',JSON.stringify({requestId:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',draft,imagePath:null}));
 });await page.reload();await expect(page.locator('#creatureSize')).toHaveValue('3 mét');await expect(page.locator('#dimension-height')).toHaveCount(0);await page.locator('.create-submit-button').click();await expect(page.getByRole('heading',{name:'Hồ sơ cũ đang chờ',exact:true})).toBeVisible();const state=await(await request.get(`${backend}/__test/state`)).json();expect(state.calls.find((c:{table:string})=>c.table==='submit_rpc').body.p_draft.traitsVersion).toBeUndefined();
});

test('failed species/element catalogs recover without clearing other form inputs',async({page,request})=>{
 await request.post(`${backend}/__test/fail`,{data:{terms:true}});await login(page);await page.locator('#creatureName').fill('Bản nháp giữ lại');await expect(page.locator('.mca-term-picker [role="alert"]')).toHaveCount(2);await request.post(`${backend}/__test/fail`,{data:{terms:false}});await page.getByRole('button',{name:'Tải lại loài sinh vật',exact:true}).click();await page.getByRole('button',{name:'Tải lại nguyên tố',exact:true}).click();await page.locator('#creatureSpecies').selectOption({label:'Thú'});await page.getByLabel('Lửa',{exact:true}).check();await expect(page.locator('#creatureName')).toHaveValue('Bản nháp giữ lại');
});

test('custom species and elements are saved and shown by their names on the detail page',async({page})=>{
 await login(page);await fill(page);await propose(page,'species','Loài lượng tử');await propose(page,'element','Thời gian');await page.getByLabel('Lửa',{exact:true}).check();await page.locator('.create-submit-button').click();await page.getByRole('link',{name:'Xem hồ sơ',exact:true}).click();await expect(page.locator('.mca-page-heading')).toContainText('Loài lượng tử');await expect(page.locator('.mca-facts-grid')).toContainText('Thời gian');await expect(page.locator('.mca-facts-grid')).toContainText('Lửa');
});
