'use client';
import {cosmicThreatNames,dimensionAxes,emptyDimensions,planetaryThreats,unitNames,type Dimensions} from '@/lib/creatures/traits';

export function DimensionFields({value,onChange}:{value?:Dimensions;onChange:(value:Dimensions)=>void}){
  const dimensions=value||emptyDimensions();return <fieldset className="mca-dimensions"><legend>Kích thước</legend><p className="mca-muted">Chỉ nhập số lớn hơn 0. Có thể để trống chiều chưa biết.</p><div className="mca-dimension-grid">{dimensionAxes.map(axis=><div key={axis.key}><label htmlFor={`dimension-${axis.key}`}>{axis.name}<input id={`dimension-${axis.key}`} type="number" inputMode="decimal" min="0" step="any" maxLength={43} value={dimensions[axis.key].value} onChange={e=>onChange({...dimensions,[axis.key]:{...dimensions[axis.key],value:e.target.value}})}/></label><label htmlFor={`unit-${axis.key}`}>Đơn vị {axis.name.toLowerCase()}<select id={`unit-${axis.key}`} value={dimensions[axis.key].unit} onChange={e=>onChange({...dimensions,[axis.key]:{...dimensions[axis.key],unit:e.target.value}})}>{Object.entries(unitNames).map(([code,name])=><option value={code} key={code}>{name}</option>)}</select></label></div>)}</div></fieldset>;
}
export function ThreatFields({id,value,onChange,disabled=false,legacy=false,label='Cấp đe dọa đề xuất'}:{id:string;value:string;onChange:(value:string)=>void;disabled?:boolean;legacy?:boolean;label?:string}){
  const main=planetaryThreats.includes(value as typeof planetaryThreats[number])?'S':value;
  return <div><label htmlFor={id}>{label}<select id={id} value={main} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Chọn cấp đe dọa...</option>{Object.entries(cosmicThreatNames).map(([code,name])=><option key={code} value={code}>{name}</option>)}{legacy&&<optgroup label="Mã trong hồ sơ cũ"><option value="SS">SS (cũ)</option><option value="X">X (cũ)</option></optgroup>}</select></label>{main==='S'&&<label htmlFor={`${id}-planetary`}>Nhánh trong hành tinh<select id={`${id}-planetary`} disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}>{planetaryThreats.map(code=><option key={code} value={code}>{code==='S'?'S — Đạt cấp (1) Phá Tinh':code}</option>)}</select><small>F → E → D → C → B → A → S. Cấp S tương đương Phá Tinh.</small></label>}</div>;
}
