import { readFile } from 'node:fs/promises';
const audit=JSON.parse(await readFile(new URL('../../supabase/audits/20261006-before-phase3.json',import.meta.url),'utf8'));
const q=value=>`"${value.replaceAll('"','""')}"`;
const types={int8:'bigint',int4:'integer',text:'text',uuid:'uuid',timestamptz:'timestamptz'};

/** Reconstruct only the reviewed public schema/ACLs in a disposable test database.
 * Auth/Storage are minimal local stand-ins; no online connection is used. */
export function auditedSchema() {
  const sql=[`create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;
    create schema auth; create schema storage;
    grant usage on schema public,auth,storage to anon,authenticated,service_role;
    create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}'::jsonb);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid; $$;
    create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets,name text,owner_id text,metadata jsonb);
    alter table storage.objects enable row level security;
    create function storage.foldername(name text) returns text[] language sql immutable as $$ select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1]; $$;`];
  for (const table of audit.tables) {
    const columns=audit.columns.filter(c=>c.table_name===table.relname).sort((a,b)=>a.ordinal_position-b.ordinal_position).map(c=>{
      if (!types[c.udt_name]) throw new Error(`Unreviewed type ${c.udt_name}`);
      return `${q(c.column_name)} ${types[c.udt_name]}${c.is_identity==='YES' ? ' generated by default as identity' : c.column_default ? ` default ${c.column_default}` : ''}${c.is_nullable==='NO'?' not null':''}`;
    });
    sql.push(`create table public.${q(table.relname)}(${columns.join(',')});`);
  }
  // Primary/unique constraints must precede foreign keys.
  for (const constraint of [...audit.constraints].sort((a,b)=>Number(a.definition.startsWith('FOREIGN'))-Number(b.definition.startsWith('FOREIGN')))) {
    sql.push(`alter table public.${q(constraint.table.replace(/^public\./,''))} add constraint ${q(constraint.name)} ${constraint.definition};`);
  }
  for (const table of audit.tables) if (table.relrowsecurity) sql.push(`alter table public.${q(table.relname)} enable row level security;`);
  const signatures=new Set(['handle_new_user()','is_admin()','admin_review_creature(bigint,text,text)']);
  for(const fn of audit.functions) {
    if (!signatures.has(fn.signature.replace(/^public\./,''))) throw new Error('Unreviewed fixture function');
    sql.push(`${fn.definition};`);
    sql.push(`revoke all on function public.${fn.signature.replace(/^public\./,'')} from public,anon,authenticated,service_role;`);
    for(const acl of fn.permissions || ['=X/postgres']) {
      const match=acl.match(/^([^=]*)=([X*]+)\//);
      if(!match)throw new Error('Unreviewed function ACL');
      sql.push(`grant execute on function public.${fn.signature.replace(/^public\./,'')} to ${match[1]?q(match[1]):'public'}${match[2].includes('*')?' with grant option':''};`);
    }
  }
  for (const trigger of audit.triggers) sql.push(`${trigger.definition};`);
  for (const policy of audit.policies) sql.push(`create policy ${q(policy.policyname)} on ${q(policy.schemaname)}.${q(policy.tablename)} as ${policy.permissive} for ${policy.cmd} to ${policy.roles.map(r=>r==='public'?'public':q(r)).join(',')}${policy.qual ? ` using (${policy.qual})` : ''}${policy.with_check ? ` with check (${policy.with_check})` : ''};`);
  for (const grant of audit.table_grants) sql.push(`grant ${grant.privilege_type} on ${q(grant.table_schema)}.${q(grant.table_name)} to ${grant.grantee==='PUBLIC'?'public':q(grant.grantee)};`);
  for (const grant of audit.column_grants) sql.push(`grant ${grant.privilege_type}(${q(grant.column_name)}) on public.${q(grant.table_name)} to ${grant.grantee==='PUBLIC'?'public':q(grant.grantee)};`);
  sql.push(`insert into storage.buckets values('creature-images','creature-images',true,null,null);`);
  // Simulate Supabase's default grants on newly created public objects too.
  sql.push('alter default privileges in schema public grant all on tables to anon,authenticated,service_role;alter default privileges in schema public grant execute on functions to anon,authenticated,service_role;');
  return sql.join('\n');
}
