-- TEST FIXTURE ONLY, not a schema export from the live Supabase project.
create role anon nologin;
create role authenticated nologin;
create schema auth;
create schema storage;
grant usage on schema public,auth,storage to anon,authenticated;
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;
$$;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}'::jsonb);
create table public.profiles(id uuid primary key references auth.users,username text,avatar_url text,role text default 'user',investigator_level text default 'Cấp I',reputation integer default 0,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.creatures (
  id bigint generated by default as identity primary key,creator_id uuid references auth.users,
  creature_code text unique,name text not null,species text not null,universe text not null,galaxy text,planet text not null,
  world text,age text,size text,element text,rarity text,power_source text,proposed_threat_level text,verified_threat_level text,
  description text not null,appearance text,weaknesses text not null,limitations text,strongest_ability_condition text,
  image_url text,status text default 'pending',created_at timestamptz default now(),updated_at timestamptz
);
create table public.creature_abilities(id bigint generated by default as identity primary key,creature_id bigint references public.creatures on delete cascade,ability_name text not null,ability_description text);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets,name text,owner_id text,metadata jsonb);
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable as $$
  select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1];
$$;
insert into auth.users(id) values ('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222'),('33333333-3333-4333-8333-333333333333');
insert into public.profiles(id,username,role) select id,id::text,case when id::text like '2222%' then 'admin' else 'user' end from auth.users;
insert into storage.buckets values ('creature-images','creature-images',true,null,null),('other','other',false,null,null);
insert into public.creatures(creator_id,name,species,universe,planet,description,weaknesses)
values ('11111111-1111-4111-8111-111111111111','Existing creature','beast','Universe','Planet','Existing description remains unchanged.','Light');
-- Deliberately broad old policies and column grants exercise restrictive gates.
alter table public.profiles enable row level security;
alter table public.creatures enable row level security;
alter table public.creature_abilities enable row level security;
create policy old_profile_all on public.profiles for all to public using (true) with check (true);
create policy old_creature_all on public.creatures for all to public using (true) with check (true);
create policy old_ability_all on public.creature_abilities for all to public using (true) with check (true);
create policy old_storage_all on storage.objects for all to public using (true) with check (true);
grant all on public.profiles,public.creatures,public.creature_abilities,storage.objects to anon,authenticated;
grant update(role,reputation) on public.profiles to anon,authenticated;
create function public.admin_review_creature(bigint,text,text) returns void language sql security definer as $$select;$$;
-- Simulate a constraint or business trigger that rejects one ability after parent insertion.
create function public.test_reject_ability() returns trigger language plpgsql as $$begin
  if new.ability_name='FORCE_DB_FAILURE' then raise exception 'TEST_DB_FAILURE'; end if; return new;
end$$;
create trigger test_ability_failure before insert on public.creature_abilities for each row execute function public.test_reject_ability();
